### ISSUE TITLE
How would I add this to the Mongo Client constructor?

### ISSUE THREAD

**Issue by Bass-Master** [erikc5000/nest-mongodb#4]
(node:14719) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and  will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

HelloI can fix this using regular node, I cant seem to fix this in nest whether using nest-mongodb or the nestjs way.

would you have any suggestions?

thank you for your help!

Adan

**Comment by erikc5000** [comment]
You should be able to pass in options directly to the `MongoClient` via the `options` property when using `MongoModule.forRoot()` or the `clientOptions` that are a part of the `MongoModuleOptions` when using `MongoModule.forRootAsync()`.

**Comment by Bass-Master** [comment]
Thank you, will implement ASAP!

Adan
