### ISSUE TITLE
Documentation: Are client and connection shared between modules?

### ISSUE THREAD

**Issue by florianbepunkt** [erikc5000/nest-mongodb#6]
I followed the mongoose docs as well as the docs of this repo.

Lets say I have three modules, each of them importing the MongoModule without specifying a connection name

```
@Module({
    imports: [MongoModule.forRoot('mongodb://localhost', "myDbName", {someOptions: ...})]
})
export class ModuleA {}

...

@Module({
    imports: [MongoModule.forRoot('mongodb://localhost', "myDbName", {someOptions: ...})]
})
export class ModuleC {}
```

Would these three modules share the same mongodb client and connection? Or would there be three different connections? I'm asking since I use mongodb field level encryption. When using it, the mongodb library client spawns an additional process and I want to make sure that all three modules use the same underlying client.

**Comment by erikc5000** [comment]
It's a been a while since I've really dug into this stuff, but I believe that as long as you pass in the same `connectionName` to `forRoot()`, which defaults to `DEFAULT_MONGO_CONNECTION_NAME`, a single MongoDB connection will be reused between modules. Don't quote me on that though. 🙂
